### ISSUE TITLE
Windows: ENOENT when running gr discover with no EDITOR environment variable set

### ISSUE THREAD

**Issue by aparovysnik** [mixu/gr#46]
Trying to run `gr discover` without EDITOR system environment variable results in following message (which is not sufficiently descriptive):

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn nano ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
```

As a user, I would like to have a more informative message and documentation with instructions on setting up the environment so git-run can operate successfully.

NOTE: this also occurs in GIT command line despite it having VIM as its own default text editor.

Workaround: set EDITOR environment variable to point to the executable of your chosen command line text editor.

**Comment by mickaelperrin** [comment]
Problem confirmed and workaround works also. Note that the EDITOR must be set and the executable path must be correct.

Thanks.

**Comment by petercoulton** [comment]
Same error with EDITOR set to `subl -w` or `atom -w`.

```
Error: spawn subl -w ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

My workaround for now is just to temporarily set EDITOR to something more shell friendly 

```
 $ EDITOR=vim gr discover .
```
