### ISSUE TITLE
`gr status` causes TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by emilyhou** [mixu/gr#88]
Trying to run `gr status`:

```
$ gr status
/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/lib/command-requirements.js:8
    if (gitCommand.stderr.toString().replace(/(\r\n|\n|\r)/gm, '').trim()) {
                          ^

TypeError: Cannot read property 'toString' of null
    at Object.git (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/lib/command-requirements.js:8:27)
    at Object.module.exports [as handle] (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/plugins/status.js:27:28)
    at next (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/index.js:244:11)
    at next (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/index.js:227:14)
    at next (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/index.js:227:14)
    at next (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/index.js:227:14)
    at next (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/index.js:227:14)
    at next (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/index.js:227:14)
    at next (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/index.js:227:14)
    at next (/Users/emilyhou/.nvm/versions/node/v8.11.1/lib/node_modules/git-run/index.js:227:14)
```

Thanks for this awesome tool!

**Comment by jamiebarrow** [comment]
@emilyhou have you already discovered your repositories? I had this same issue, but then what happened is I did not tag my repositories that it discovered, and so it was not saving them in the `~/.grconfig.json` file. When you run the discover, don't forget to include the `@tags`, and then try again?

**Comment by emilyhou** [comment]
@jamiebarrow Thanks, tried to run discover but it failed to discover any of my repositories that I wanted it to see, and I ran it straight from the parent directory containing all the repos. I'll try debugging this on the side but it sounds like this bug is a WAI, although the error message could be a bit more informative!
